console.log("Hello, World!");
console.log("This is a test script.");
console.log("Running a simple JavaScript test.");
console.log("End of test script.");
console.log("All done!");
console.log("No errors encountered.");
console.log("Test completed successfully.");
console.log("Thank you for running the test.");
console.log("Goodbye!");
console.log("This is the last line of the test.");
console.log("Final message: Test script executed.");
console.log("Script execution finished.");
console.log("Exiting the script now.");
console.log("Script has ended.");
console.log("Thank you for your attention.");